import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

interface ColorToken {
  name: string;
  value: {
    dark: string;
    light: string;
  };
  usage: string;
}

interface TypeStyle {
  name: string;
  fontSize: string;
  lineHeight?: number | string;
  fontWeight?: number | string;
  letterSpacing?: string;
  sample?: string;
  usage?: string;
}

interface TypeGroup {
  name: string;
  family: string;
  styles: TypeStyle[];
}

interface SpacingToken {
  name: string;
  value: string;
  usage: string;
}

interface RadiusToken {
  name: string;
  value: string;
  usage: string;
}

interface SizeToken {
  name: string;
  value: string;
  usage: string;
}

interface TokensData {
  name: string;
  version: number;
  color: {
    themes: { id: string; name: string }[];
    tokens: ColorToken[];
  };
  type: {
    fonts: unknown[];
    families: {
      sans: string;
      mono: string;
    };
    groups: TypeGroup[];
  };
  spacing: {
    tokens: SpacingToken[];
  };
  radius: {
    tokens: RadiusToken[];
  };
  size: {
    tokens: SizeToken[];
  };
}

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const packageDir = path.resolve(__dirname, "..");

const tokensJsonPath = path.join(packageDir, "src", "theme", "tokens.json");
const tokensCssPath = path.join(packageDir, "src", "theme", "tokens.css");
const tailwindThemeCssPath = path.join(packageDir, "src", "theme", "tailwind-theme.css");

function generateTokensCss(tokens: TokensData): string {
  const lines: string[] = [
    "/* Generated by scripts/build-tokens.ts. Do not edit directly. */",
    "",
    ":root {",
    `  --font-sans: ${tokens.type.families.sans};`,
    `  --font-mono: ${tokens.type.families.mono};`,
  ];

  for (const token of tokens.spacing.tokens) {
    lines.push(`  --${token.name}: ${token.value};`);
  }

  for (const token of tokens.radius.tokens) {
    lines.push(`  --${token.name}: ${token.value};`);
  }

  for (const token of tokens.size.tokens) {
    lines.push(`  --${token.name}: ${token.value};`);
  }

  lines.push("}");
  lines.push("");

  lines.push(":root,");
  lines.push('[data-theme="dark"] {');
  for (const token of tokens.color.tokens) {
    lines.push(`  --${token.name}: ${token.value.dark};`);
  }
  lines.push("}");
  lines.push("");

  lines.push('[data-theme="light"] {');
  for (const token of tokens.color.tokens) {
    lines.push(`  --${token.name}: ${token.value.light};`);
  }
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

function generateTailwindThemeCss(tokens: TokensData): string {
  const lines: string[] = [
    "/* Generated by scripts/build-tokens.ts. Do not edit directly. */",
    "",
    "@theme inline {",
    "  --color-*: initial;",
    "  --radius-*: initial;",
    "  --text-*: initial;",
    "  --font-*: initial;",
    "",
  ];

  for (const token of tokens.color.tokens) {
    lines.push(`  --color-${token.name}: var(--${token.name});`);
  }

  lines.push("");
  lines.push("  --font-sans: var(--font-sans);");
  lines.push("  --font-mono: var(--font-mono);");
  lines.push("");

  for (const group of tokens.type.groups) {
    for (const style of group.styles) {
      lines.push(`  --text-${style.name}: ${style.fontSize};`);
      if (style.lineHeight !== undefined) {
        lines.push(`  --text-${style.name}--line-height: ${style.lineHeight};`);
      }
      if (style.fontWeight !== undefined) {
        lines.push(`  --text-${style.name}--font-weight: ${style.fontWeight};`);
      }
      if (style.letterSpacing !== undefined) {
        lines.push(`  --text-${style.name}--letter-spacing: ${style.letterSpacing};`);
      }
    }
  }

  lines.push("");
  lines.push("  --spacing: var(--space-1);");
  lines.push("");

  for (const token of tokens.radius.tokens) {
    lines.push(`  --${token.name}: var(--${token.name});`);
  }

  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

function main(): void {
  const isCheck = process.argv.includes("--check");
  const rawData = fs.readFileSync(tokensJsonPath, "utf-8");
  const tokens = JSON.parse(rawData) as TokensData;

  const expectedTokensCss = generateTokensCss(tokens);
  const expectedTailwindCss = generateTailwindThemeCss(tokens);

  if (isCheck) {
    let stale = false;
    if (
      !fs.existsSync(tokensCssPath) ||
      fs.readFileSync(tokensCssPath, "utf-8").replace(/\r\n/g, "\n") !== expectedTokensCss
    ) {
      stale = true;
    }
    if (
      !fs.existsSync(tailwindThemeCssPath) ||
      fs.readFileSync(tailwindThemeCssPath, "utf-8").replace(/\r\n/g, "\n") !== expectedTailwindCss
    ) {
      stale = true;
    }
    if (stale) {
      console.error(
        "Theme tokens CSS is stale. Run 'pnpm --filter @nova/ui-core tokens' to regenerate.",
      );
      process.exit(1);
    }
    console.log("Theme tokens CSS is up to date.");
    process.exit(0);
  }

  fs.writeFileSync(tokensCssPath, expectedTokensCss, "utf-8");
  fs.writeFileSync(tailwindThemeCssPath, expectedTailwindCss, "utf-8");
  console.log("Theme tokens CSS generated successfully.");
}

main();
