"""All tables of schema v1 (D37). Import from here so `Base.metadata` is complete."""

from nova_db.models.auth import ApprovalRequest, AuthSession, Role, User, UserRole
from nova_db.models.backtest import (
    BacktestResult,
    BacktestRun,
    IntradayDecision,
    IntradayTrade,
    ResearchProfile,
    ResearchProfileVersion,
    Trade,
)
from nova_db.models.base import Base
from nova_db.models.broker import (
    BrokerAccount,
    BrokerKiteApp,
    BrokerProfile,
    BrokerSession,
    RateLimitRule,
    RecorderSetting,
)
from nova_db.models.coverage import COVERAGE_TIMEFRAMES, CandleDay, UnavailableDay
from nova_db.models.data import (
    AuditEntry,
    Candle,
    ChargeRate,
    DataJob,
    DataJobStep,
    DownloadSetting,
    IndexTick,
    Instrument,
    MarketIndex,
    Tick,
    TickCheck,
    TickDay,
    TickSession,
    UniverseEntry,
)
from nova_db.models.strategy import Strategy, StrategyVersion

__all__ = [
    "ApprovalRequest",
    "AuditEntry",
    "AuthSession",
    "BacktestResult",
    "BacktestRun",
    "Base",
    "BrokerAccount",
    "BrokerKiteApp",
    "BrokerProfile",
    "BrokerSession",
    "COVERAGE_TIMEFRAMES",
    "Candle",
    "CandleDay",
    "ChargeRate",
    "DataJob",
    "DataJobStep",
    "DownloadSetting",
    "Instrument",
    "IndexTick",
    "IntradayDecision",
    "IntradayTrade",
    "MarketIndex",
    "RateLimitRule",
    "RecorderSetting",
    "ResearchProfile",
    "ResearchProfileVersion",
    "Role",
    "Strategy",
    "StrategyVersion",
    "Tick",
    "TickCheck",
    "TickDay",
    "TickSession",
    "Trade",
    "UniverseEntry",
    "UnavailableDay",
    "User",
    "UserRole",
]
