"""Pydantic models mirroring `@nova/contracts` (D34)."""

from nova_contracts.audit import AuditAction, AuditEntry, AuditTargetType
from nova_contracts.auth import LoginRequest
from nova_contracts.backtest import (
    BacktestMetrics,
    BacktestResult,
    BacktestRun,
    BacktestRunCreate,
    BacktestRunStatus,
    EquityPoint,
    SymbolBreakdown,
    Universe,
)
from nova_contracts.broker import (
    Broker,
    BrokerAccount,
    BrokerAccountCreate,
    BrokerLink,
    BrokerLinkKind,
    BrokerProfile,
    BrokerSession,
    BrokerSessionStatus,
)
from nova_contracts.charges import Charges
from nova_contracts.common import (
    Contract,
    Email,
    Exchange,
    Id,
    IsoDate,
    NonNegPaise,
    Paise,
    Segment,
    Side,
    Timeframe,
    UtcDateTime,
)
from nova_contracts.data_job import (
    MAX_DOWNLOAD_SYMBOLS,
    DataJob,
    DataJobCreate,
    DataJobStatus,
    DataJobType,
)
from nova_contracts.error import ApiError, ApiErrorBody, ApiErrorCode
from nova_contracts.indicators import INDICATORS, Indicator, IndicatorName, check_params
from nova_contracts.market_data import Candle, IndexName, Instrument
from nova_contracts.page import PAGE_LIMIT_DEFAULT, PAGE_LIMIT_MAX, Page
from nova_contracts.rate_limit import (
    RateLimit,
    RateLimitEndpoint,
    RateLimitRule,
    RateLimitUpdate,
    RateLimitWindow,
)
from nova_contracts.strategy import (
    Condition,
    Operand,
    RuleGroup,
    Sizing,
    Strategy,
    StrategyCreate,
    StrategySpec,
    StrategySpecPython,
    StrategySpecVisual,
    StrategyStatus,
    StrategyUpdate,
    StrategyVersion,
    StrategyVersionCreate,
)
from nova_contracts.strategy_stats import BestNetPnl, StrategyStats
from nova_contracts.trade import Trade
from nova_contracts.universe import InstrumentSyncResult, UniverseEntry, UniverseEntryWrite
from nova_contracts.user import User, UserRole

__all__ = [
    "INDICATORS",
    "MAX_DOWNLOAD_SYMBOLS",
    "PAGE_LIMIT_DEFAULT",
    "PAGE_LIMIT_MAX",
    "AuditAction",
    "AuditEntry",
    "AuditTargetType",
    "BacktestMetrics",
    "BacktestResult",
    "BacktestRun",
    "BacktestRunCreate",
    "BacktestRunStatus",
    "BestNetPnl",
    "Broker",
    "BrokerAccount",
    "BrokerAccountCreate",
    "BrokerLink",
    "BrokerLinkKind",
    "BrokerProfile",
    "BrokerSession",
    "BrokerSessionStatus",
    "DataJob",
    "DataJobCreate",
    "DataJobStatus",
    "DataJobType",
    "Candle",
    "Charges",
    "Condition",
    "Email",
    "EquityPoint",
    "IndexName",
    "Indicator",
    "IndicatorName",
    "Instrument",
    "InstrumentSyncResult",
    "LoginRequest",
    "Operand",
    "Page",
    "RateLimit",
    "RateLimitEndpoint",
    "RateLimitRule",
    "RateLimitUpdate",
    "RateLimitWindow",
    "ApiError",
    "ApiErrorBody",
    "ApiErrorCode",
    "Contract",
    "Exchange",
    "Id",
    "IsoDate",
    "NonNegPaise",
    "Paise",
    "RuleGroup",
    "Segment",
    "Sizing",
    "Strategy",
    "StrategyCreate",
    "StrategySpec",
    "StrategySpecPython",
    "StrategySpecVisual",
    "StrategyStats",
    "StrategyStatus",
    "StrategyUpdate",
    "StrategyVersion",
    "StrategyVersionCreate",
    "SymbolBreakdown",
    "Side",
    "Timeframe",
    "Trade",
    "Universe",
    "UniverseEntry",
    "UniverseEntryWrite",
    "User",
    "UserRole",
    "check_params",
    "UtcDateTime",
]
